name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image with secret mounts
        run: |
          docker build \
            --secret id=slack_bot_token,env=SLACK_BOT_TOKEN_PROD \
            --secret id=slack_signing_secret,env=SLACK_SIGNING_SECRET_PROD \
            --secret id=ngrok_authtoken,env=NGROK_AUTHTOKEN_PROD \
            --secret id=port,env=PORT_PROD \
            --secret id=channel_id,env=CHANNEL_ID_PROD \
            -t ghcr.io/youruser/campsite-bot:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/youruser/campsite-bot:latest

      - name: Notify Pi webhook
        run: |
          curl -X POST https://campsitebot.kozow.com/deploy
