name: Deploy Docker image to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          IMAGE_BASE=us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/campsite-availability-scanner/campsite-availability-scanner
          docker build -t $IMAGE_BASE:${{ github.sha }} -t $IMAGE_BASE:latest .

      - name: Push Docker image (both tags)
        run: |
          IMAGE_BASE=us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/campsite-availability-scanner/campsite-availability-scanner
          docker push $IMAGE_BASE:${{ github.sha }}
          docker push $IMAGE_BASE:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy campsite-availability-scanner \
            --image us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/campsite-availability-scanner/campsite-availability-scanner:${{ github.sha }} \
            --region us-west1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars ENV=production,SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN_PROD }},SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET_PROD }},CHANNEL_ID=${{ secrets.CHANNEL_ID_PROD }},APP_URL=${{ secrets.CLOUD_RUN_URL }}
